### ISSUE TITLE
Tracking v1.0

### ISSUE THREAD

**Issue by roman-yagodin** [roman-yagodin/R7.Webmate#6]
In general, we need working TextCleaner and TableCleaner features for v1.0.

- [ ] Proper XML entities replacement (to/from Unicode chars, to/from named entities).
- [ ] html-to-html processing should properly process text inside tags and text in selected attributes (alt, title).
- [ ] Allow to copy HTML from results.
- [ ] Message area.
- [ ] Progress bar.  
- [ ] Drag&drop paste.

Tests and more tests.
